### PR TITLE
NEP29 + Py312

### PR DESCRIPTION
**Pull request by IAlibay**

### CODE REVIEW

**Review by hmacdope — APPROVED** [review]
LGTM thanks for doing this, i have been a bit slow.

**Comment by IAlibay** [comment]
That PR was failing, not sure why it got merged O.o

Do you want to revert @hmacdope ?

**Comment by hmacdope** [comment]
@IAlibay I figured CI changes would illustrate that our 3.12 build wasn't working, because of #104, and that it would better demonstrate that, what do you think.

**Comment by IAlibay** [comment]
There's a catch to this approach, which is that you don't know that the packaging / CI changes are correct until CI actually goes green. It is, in my opinion, always better to try to fix the problem and merge on green rather than try to fix two moving parts at the same time. It's especially true here where the problem is down to a packaging issue.

**Pull request merged**
