### PR TITLE
fix bug in frame read (chemfiles #425)

### LINKED ISSUE #92: Possible issues with tng_util_trajectory_next_frame_present_data_blocks_find
Some possible issues withtng_util_trajectory_next_frame_present_data_blocks_find were identified in `Chemfiles`:

See https://github.com/chemfiles/chemfiles/pull/430 and https://gitlab.com/gromacs/tng/-/issues/18.

AFAIK, there is no problem in PyTNG ATM as the `step` variable is returned incorrect and we don't use it, but would be good patch when fixed upstream

### PR DESCRIPTION
**Pull request by hmacdope**
Fixes #92. 

Bug identified in frame counter by chemfiles. Fixed here using a git patch.

See chemfiles/chemfiles#430 and https://gitlab.com/gromacs/tng/-/issues/18.

### CODE REVIEW

**Review by orbeckst — CHANGES_REQUESTED** [review]
It would be good to have the test from https://gitlab.com/gromacs/tng/-/issues/18 or something like it to show that the bug is fixed.

**Comment by hmacdope** [comment]
@orbeckst we call the function that **was** faulty at the C level, but never  actually expose or use the previously incorrect `step` data as read by this function at any point.

This makes this change silent with respect to pytng as *currently* it stands, but is important for C library correctness.

What I guess i'm trying to say is that to test this would require changes to the cython layer to expose the `step` data. Do we think this is worth it? Open to suggestions.

**Comment by orbeckst** [comment]
The ideal solution, I think, would expose it at the cython layer so that you can write a test to check that it works as expected.

How much does our C code agree with the one in the GROMACS TNG repo?

I'd be ok with any untested changes that are also in the main repo. If it's not there (i.e., code diverges) then we should have a test.

**Comment by orbeckst** [comment]
(However, I am not doing the work here so that's just my opinion. What do you think how we should handle this?)

**Comment by hmacdope** [comment]
> How much does our C code agree with the one in the GROMACS TNG repo?

Almost exactly, this is the first diverging change. 

> The ideal solution, I think, would expose it at the cython layer so that you can write a test to check that it works as expected.

I agree that divergence means we should test. I will expose the data at the cython level as a private attr.

**Comment by hmacdope** [comment]
Upon further reflection and code introspection, this doesn't make a whole lot of sense to test given the way PyTNG is written.

 We only call this function once on  `__init__()` and discard the step information. Perhaps we should be calling it more often (see #88) but that is a seperate discussion. 

It is still opaque to me whether all the TNG blocks **MUST** be written at step 0 or even are by gromacs, see [this](https://github.com/gromacs/gromacs/blob/880dfefe5f0a57ad1a9e5af90ed75c701a880f8d/src/gromacs/fileio/tngio.cpp) file for how gromacs writes TNG files. Perhaps @acmnpv can clarify this from a GROMACS perspective?

The bug that this PR fixes can only be detected by **iterating** through the **whole** file with the `tng_util_trajectory_next_frame_present_data_blocks_find()` function and examining the step data. To change to this system would require a rewrite.

As is the step data we read on our one and only `__init__()` call is useless as it will invariably be 0 all the time. 

@orbeckst I would be keen to hear further thoughts :)

**Comment by hmacdope** [comment]
@orbeckst you happy with the note added here?

**Review by orbeckst — APPROVED** [review]

**Comment by orbeckst** [comment]
Sorry @hmacdope , this review just dropped of my radar. Thanks for the reminder.

**Pull request merged**
