### PR TITLE
Fixing TNG iteration

### PR DESCRIPTION
**Pull request by richardjgowers**
So it looks like the `pos_read_range` function expects frame numbers in terms of the global MD step counter, rather than relative to the number of frames.

This seems to start to fix TNG file reading....

### CODE REVIEW

**Comment by richardjgowers** [comment]
@kain88-de not sure how much you remember this, but turns out the reason why TNG never worked on real cases was most instances of "frame" for TNG refer to the global frame index, rather than the nth frame actually saved in the file.  So unless you're saving frames every frame, you have to do a lot more work to iterate!

**Comment by kain88-de** [comment]
I'm sorry I don't remember much about TNG

**Comment by orbeckst** [comment]
> So it looks like the pos_read_range function expects frame numbers in terms of the global MD step counter, rather than relative to the number of frames.

This sounds like DCD in CHARMM which looks at integrator timesteps. (Sorry, useless historical knowledge is my only contribution here...)

**Comment by orbeckst** [comment]
Btw, what's a "Draft PR" – is this a new thing on GitHub?

**Comment by richardjgowers** [comment]
Yeah new github thing, can’t merge until I switch it, what we used to call a WIP PR
  

  
  

  
  
>

**Comment by hmacdope** [comment]
Can I close this friends? @richardjgowers @orbeckst @kain88-de ?

**Comment by orbeckst** [comment]
Almost certainly... but give @richardjgowers a day to reply.

**Pull request closed without merging**
